### ISSUE TITLE
Coffee Weather Desktop Install Error

### ISSUE THREAD

**Issue by CodeTazMan** [nick92/coffee#25]
sudo add-apt-repository ppa:coffee-team/coffee && sudo apt update

Reading package lists... Done               
E: The repository 'http://ppa.launchpad.net/coffee-team/coffee/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

What would be my next step now?

**Comment by Ciolloi** [comment]
Same on Ubuntu 19.04

Ign:1 http://ppa.launchpad.net/coffee-team/coffee/ubuntu disco InRelease
Hit:2 http://archive.canonical.com/ubuntu disco InRelease
Hit:3 http://archive.ubuntu.com/ubuntu disco InRelease                   
Err:4 http://ppa.launchpad.net/coffee-team/coffee/ubuntu disco Release   
  404  Not Found [IP: 91.189.95.83 80]
Get:5 http://archive.ubuntu.com/ubuntu disco-updates InRelease [88,4 kB]
Hit:6 http://archive.ubuntu.com/ubuntu disco-backports InRelease
Hit:7 http://archive.ubuntu.com/ubuntu disco-security InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/coffee-team/coffee/ubuntu disco Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Is not released for Ubuntu 19.04? Should I roll back to Ubuntu 18.10?

**Comment by nick92** [comment]
Coffee is now available in 18.10 & 19.04

**Comment by fodongkara** [comment]
May you please make it available for 20.04?
