### ISSUE TITLE
PPA no longer available

### ISSUE THREAD

**Issue by ghost** [nick92/coffee#29]
Running elementary Juno.  I am getting 404's when I try to even add the PPA, so is it temporarily out of service or just permanently gone?

**Comment by nick92** [comment]
It isn't currently released in the latest LTS version of Ubuntu 18.04 (which I think Juno is running), am working on a new release of Coffee so will be released in 18.04 when finished

**Comment by nick92** [comment]
Coffee is now available in 18.04 and 18.10, see [release notes](https://github.com/nick92/coffee/releases/tag/2.2.0)
