### ISSUE TITLE
spreken ze doich?

### ISSUE THREAD

**Issue by zip9** [nick92/coffee#30]
No sorry I don't, but would like to view articles from Wired in english. Any chance there could be an optioni for preferred language? Or base the language on the weather location (which may not always be correct).
 Also notice if selecting the letter G icon (Google search?) coffee opens as a blank rectangle (not even weather appears). Perhaps I don't understand how that works....thanks for this useful Applet.

**Comment by nick92** [comment]
This issue is resolved in release [2.2.0](https://github.com/nick92/coffee/releases/tag/2.2.0)

You are now able to filter news on language, you may have to give more detail on the second issue as I don't understand what you mean
